### ISSUE TITLE
Share impact through social media - what should the tweet/Facebook text be?

### ISSUE THREAD

**Issue by kalinn** [davisshaver/phillydrinktax#4]

**Comment by davisshaver** [comment]
Here's what the share prompt says right now

![screen shot 2015-05-08 at 9 17 43 am](https://cloud.githubusercontent.com/assets/1636964/7536993/1e2bd18c-f563-11e4-957f-125901cf6a4a.png)

:shipit:

**Comment by mikethomaspsu** [comment]
Can we change this to say what the tax funds? Maybe "I contribute about
$421 each year to Philly's schools. Find out your impact: phillydrinktax.com
via @beninphilly" ?

On Friday, May 8, 2015, davisshaver notifications@github.com wrote:

> Here's what the share prompt says right now
> 
> [image: screen shot 2015-05-08 at 9 17 43 am]
> https://cloud.githubusercontent.com/assets/1636964/7536993/1e2bd18c-f563-11e4-957f-125901cf6a4a.png
> 
> [image: :shipit:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/davisshaver/phillydrinktax/issues/4#issuecomment-100229181
> .

## 

Mike Thomas
(610) 585-9710

@MikeThomasPSU
